/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package online.krsk.rekurs.IO;

import java.awt.Dimension;
import java.io.File;
import java.io.FilenameFilter;
import java.io.IOException;
import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextArea;


/**
 *
 * @author admin2
 */
public class TitleFrame extends javax.swing.JFrame{

    public File path, pathXLS;
    public JTextArea textArea;
    public static String strFilter = "cab";
    boolean flagZIP=false, flagCAB=false;
    public Thread th = Thread.currentThread();
    boolean flagThread=false;
    
    /**
     * Creates new form TitleFrame
     */
    public TitleFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Выбрать каталог с CAB-архивами");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setText("c:\\temp");

        jButton2.setText("Выбрать каталог для XLS файлов");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel2.setText("c:\\temp\\");

            jButton3.setText("Распаковать");
            jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton3MouseClicked(evt);
                }
            });

            jTextArea1.setColumns(20);
            jTextArea1.setRows(5);
            jTextArea1.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jTextArea1MouseClicked(evt);
                }
            });
            jScrollPane1.setViewportView(jTextArea1);

            jButton4.setText("Компилировать");
            jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    jButton4MouseClicked(evt);
                }
            });

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton3)
                            .addGap(31, 31, 31)
                            .addComponent(jButton4)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap())
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jLabel2))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton4))
                    .addContainerGap())
            );

            jButton3.getAccessibleContext().setAccessibleDescription("");

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        // TODO add your handling code here:
        JFileChooser jfCh = new JFileChooser();
        jfCh.setDialogTitle("Выбор директории с *.cab файлами");
        jfCh.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = jfCh.showOpenDialog(TitleFrame.this);
        if (result == JFileChooser.APPROVE_OPTION )
            //JOptionPane.showMessageDialog(TitleFrame.this, jfCh.getSelectedFile());
        this.path = jfCh.getSelectedFile();
        
        jLabel1.setText(this.path.getAbsolutePath());
        
        if (jLabel1.getText().length()==3) 
            {jLabel2.setText(this.path+"XLS");}
        else
            {jLabel2.setText(this.path+"\\XLS");}
        this.pathXLS = new File(jLabel2.getText());
        this.pathXLS.mkdir();    
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        JFileChooser jfCh2 = new JFileChooser();
        jfCh2.setDialogTitle("Выбор директории с *.cab файлами");
        jfCh2.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = jfCh2.showOpenDialog(TitleFrame.this);
        if (result == JFileChooser.APPROVE_OPTION )
            //JOptionPane.showMessageDialog(TitleFrame.this, jfCh.getSelectedFile());
        jLabel2.setText(jfCh2.getSelectedFile().getAbsolutePath());
                
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        
        
        Unzip unzip = new Unzip(pathXLS);
        
        jTextArea1.append("Looking for *."+strFilter+" in "+path.getAbsolutePath()+":\n");
        FilenameFilter only = new Filter(strFilter);
        File f[] = path.listFiles(only);
        
    if(f.length<1){jTextArea1.append("Файлов нет\n"); return;}
        
    for (int i=0; i<f.length; i++){
            if(f[i].isFile()){
                  jTextArea1.append(f[i].getName()+"\n");
            }
    }
        jTextArea1.append("\n");
        jTextArea1.append("Распаковка в "+pathXLS.getAbsolutePath()+":\n");
    
    for(int i=0; i<f.length; i++){
          if(f[i].isFile()) 
          
           try {
              if("cab".equals(strFilter)){jTextArea1.append("Файл "+unzip.unzip7zSHELL(f[i])+" распакован\n");}
              else jTextArea1.append("Файл "+unzip.unzip(f[i])+" распакован\n");;
           } catch (Exception ex) {
              Logger.getLogger(TitleFrame.class.getName()).log(Level.SEVERE, null, ex);
           }
    
    }
    jTextArea1.append("\n");  
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        File[] listf = pathXLS.listFiles();
        File parentPath = pathXLS.getParentFile();
        ArrayList<ImportData> importDataArr = new ArrayList<>();
        ImportData importData;
        
        try {
            
            jTextArea1.append("К обработке готово: "+listf.length+" тестов\n");
            for(int i=0;i<listf.length;i++){
            
                //th.setPriority(10);
                importDataArr.add(new ImportData(pathXLS,parentPath, listf[i]));
                importData = importDataArr.get(i);
                importData.t.join();
                     
                
                jTextArea1.append(i+". "+importData.getMsg()+"\n");
                
            }
        } catch (IOException ex) {
            Logger.getLogger(TitleFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(TitleFrame.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jTextArea1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextArea1MouseClicked
        // TODO add your handling code here:
        
        
        /*for(Test test : ImportData.listTests){
            
            
          System.out.println("В тесте \""+test.nameArr[1]+ "\" следующие типы вопросов:\n");
          jTextArea1.append("В тесте \""+test.nameArr[1]+ "\" следующие типы вопросов:\n\n");
            
            for(String[] str : test.questions2){
                System.out.print("Тип: "+str[3]+ ". Вопрос: "); System.out.printf("%.30s", str[2]+"\n");
                jTextArea1.append("Тип: "+str[3]+ ". Вопрос: "+String.format("%.100s", str[2])+"\n");
                }
          
          jTextArea1.append("\n");
             
        }*/
        //System.out.println("?????????   "+ImportData.listTests.get(1).getID()+"###"+ImportData.listTests.get(1).questions2.get(9)[11]);
    }//GEN-LAST:event_jTextArea1MouseClicked
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedEncodingException{
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TitleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TitleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TitleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TitleFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            new TitleFrame().setVisible(true);
            //createGUI();
            }
        });
    }
    public static void createGUI()
    {
        JFrame frame = new JFrame("Работа с файлами");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        
        JLabel label = new JLabel("Test label");
        frame.getContentPane().add(label);
        
        frame.setPreferredSize(new Dimension(200, 100));
        
        frame.pack();
        frame.setVisible(true);          
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
